package dvt;

import dvt.Student;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Karinak
 */
public class AdminUI extends javax.swing.JFrame {
    
    /**
     * Creates new form HomeScreenWaiterUI
     */
    public AdminUI() {
        initComponents();
        DOBdatePicker.setDateToToday();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        soldButtonGroup = new javax.swing.ButtonGroup();
        confirmationSlipButtonGroup = new javax.swing.ButtonGroup();
        manageMenuPan = new javax.swing.JTabbedPane();
        manageMenuPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addItemtButton = new javax.swing.JButton();
        deleteItemButton = new javax.swing.JButton();
        editItemButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        itemNameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        itemTypeComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        itempricetextField = new javax.swing.JTextField();
        manageWorkersPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        workersTable = new javax.swing.JTable();
        waiterNameTextField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        waiterUsernameTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        viewPasswordButton = new javax.swing.JButton();
        passwordTextField = new javax.swing.JTextField();
        addWaiterButton = new javax.swing.JButton();
        editWaiterButton = new javax.swing.JButton();
        deleteWaiterButton = new javax.swing.JButton();
        FAQsPanel = new javax.swing.JPanel();
        viewSalesPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        salesTable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        mostSoldradioButton = new javax.swing.JRadioButton();
        leastSoldRadioButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        allCheckbox = new javax.swing.JCheckBox();
        sandwichtextBox = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        SaladCheckBox = new javax.swing.JCheckBox();
        snackCheckbox = new javax.swing.JCheckBox();
        drinkCheckBox = new javax.swing.JCheckBox();
        wrapCheckBox = new javax.swing.JCheckBox();
        viewSalesButton = new javax.swing.JButton();
        viewOrdersPanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ordersTable = new javax.swing.JTable();
        manageStudenstPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        surnameTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        gradeComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        classComboBox = new javax.swing.JComboBox<>();
        addStudentButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        IDtextField = new javax.swing.JTextField();
        errorMsgLabel = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        yesradioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        DOBdatePicker = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageMenuPan.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        menuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Item Type", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(menuTable);

        jLabel7.setText("MENU");

        jLabel8.setText("MANAGE MENU");

        addItemtButton.setText("ADD ITEM");
        addItemtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemtButtonActionPerformed(evt);
            }
        });

        deleteItemButton.setText("DELETE ITEM");

        editItemButton.setText("EDIT ITEM");

        jLabel9.setText("Item Name: ");

        jLabel10.setText("Item Type: ");

        itemTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandwich", "Wrap", "Drink", "Snack", "Salad" }));

        jLabel11.setText("Price: ");

        javax.swing.GroupLayout manageMenuPanelLayout = new javax.swing.GroupLayout(manageMenuPanel);
        manageMenuPanel.setLayout(manageMenuPanelLayout);
        manageMenuPanelLayout.setHorizontalGroup(
            manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageMenuPanelLayout.createSequentialGroup()
                        .addComponent(addItemtButton)
                        .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteItemButton)
                                .addGap(113, 113, 113)
                                .addComponent(editItemButton)
                                .addGap(96, 96, 96))))
                    .addGroup(manageMenuPanelLayout.createSequentialGroup()
                        .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(itempricetextField))
                            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(150, 150, 150)
                        .addComponent(jLabel10)
                        .addGap(31, 31, 31)
                        .addComponent(itemTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 152, Short.MAX_VALUE))))
            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        manageMenuPanelLayout.setVerticalGroup(
            manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageMenuPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                                .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(itempricetextField, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)))
                            .addGroup(manageMenuPanelLayout.createSequentialGroup()
                                .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(itemNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(itemTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(22, 22, 22)
                        .addComponent(addItemtButton)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageMenuPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(manageMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deleteItemButton)
                            .addComponent(editItemButton))
                        .addContainerGap())))
        );

        manageMenuPan.addTab("Manage Menu", manageMenuPanel);

        jLabel15.setText("WORKERS");

        workersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Waiter ID ", "Name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(workersTable);

        jLabel16.setText("Name: ");

        jLabel17.setText("Username: ");

        jLabel18.setText("Password: ");

        viewPasswordButton.setText("jButton1");

        addWaiterButton.setText("ADD WAITER");

        editWaiterButton.setText("EDIT WAITER");

        deleteWaiterButton.setText("DELETE WAITER");

        javax.swing.GroupLayout manageWorkersPanelLayout = new javax.swing.GroupLayout(manageWorkersPanel);
        manageWorkersPanel.setLayout(manageWorkersPanelLayout);
        manageWorkersPanelLayout.setHorizontalGroup(
            manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                .addGroup(manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel15))
                    .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(waiterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(viewPasswordButton)))
                        .addGap(47, 47, 47)
                        .addComponent(jLabel17)
                        .addGap(29, 29, 29)
                        .addComponent(waiterUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(addWaiterButton)
                .addGap(148, 148, 148)
                .addComponent(editWaiterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deleteWaiterButton)
                .addGap(69, 69, 69))
        );
        manageWorkersPanelLayout.setVerticalGroup(
            manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGroup(manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waiterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(waiterUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(manageWorkersPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)))
                .addGap(44, 44, 44)
                .addGroup(manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(viewPasswordButton)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(manageWorkersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addWaiterButton)
                    .addComponent(editWaiterButton)
                    .addComponent(deleteWaiterButton))
                .addGap(69, 69, 69))
        );

        manageMenuPan.addTab("Manage Workers", manageWorkersPanel);

        javax.swing.GroupLayout FAQsPanelLayout = new javax.swing.GroupLayout(FAQsPanel);
        FAQsPanel.setLayout(FAQsPanelLayout);
        FAQsPanelLayout.setHorizontalGroup(
            FAQsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        FAQsPanelLayout.setVerticalGroup(
            FAQsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        manageMenuPan.addTab("FAQS", FAQsPanel);

        jLabel12.setText("SALES ");

        salesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Item Type", "Item Price ", "Times Sold ", "Total sales "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(salesTable);

        jLabel13.setText("Order By ");

        soldButtonGroup.add(mostSoldradioButton);
        mostSoldradioButton.setText("Most sold");

        soldButtonGroup.add(leastSoldRadioButton);
        leastSoldRadioButton.setText("Least Sold");

        jLabel14.setText("Type");

        allCheckbox.setText("All ");

        sandwichtextBox.setText("Sandwich");

        jCheckBox2.setText("Burger");

        SaladCheckBox.setText("Salad");

        snackCheckbox.setText("Snack");

        drinkCheckBox.setText("Drink");

        wrapCheckBox.setText("Wrap");

        viewSalesButton.setText("VIEW SALES ");

        javax.swing.GroupLayout viewSalesPanelLayout = new javax.swing.GroupLayout(viewSalesPanel);
        viewSalesPanel.setLayout(viewSalesPanelLayout);
        viewSalesPanelLayout.setHorizontalGroup(
            viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSalesPanelLayout.createSequentialGroup()
                .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSalesPanelLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewSalesPanelLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewSalesPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel13)
                        .addGap(173, 173, 173)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(viewSalesPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mostSoldradioButton)
                            .addComponent(leastSoldRadioButton))
                        .addGap(135, 135, 135)
                        .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewSalesPanelLayout.createSequentialGroup()
                                .addComponent(allCheckbox)
                                .addGap(29, 29, 29)
                                .addComponent(snackCheckbox))
                            .addComponent(SaladCheckBox)
                            .addGroup(viewSalesPanelLayout.createSequentialGroup()
                                .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sandwichtextBox)
                                    .addComponent(jCheckBox2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(viewSalesPanelLayout.createSequentialGroup()
                                        .addComponent(wrapCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 198, Short.MAX_VALUE)
                                        .addComponent(viewSalesButton))
                                    .addComponent(drinkCheckBox))))))
                .addGap(38, 38, 38))
        );
        viewSalesPanelLayout.setVerticalGroup(
            viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSalesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSalesPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mostSoldradioButton)
                            .addComponent(allCheckbox)
                            .addComponent(snackCheckbox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(leastSoldRadioButton)
                            .addComponent(sandwichtextBox)
                            .addComponent(drinkCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(viewSalesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(wrapCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaladCheckBox)
                        .addContainerGap(148, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewSalesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewSalesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        manageMenuPan.addTab("View Sales", viewSalesPanel);

        jLabel19.setText("ORDERS");

        ordersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Student Name", "Order", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(ordersTable);

        javax.swing.GroupLayout viewOrdersPanelLayout = new javax.swing.GroupLayout(viewOrdersPanel);
        viewOrdersPanel.setLayout(viewOrdersPanelLayout);
        viewOrdersPanelLayout.setHorizontalGroup(
            viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                .addGroup(viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel19))
                    .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        viewOrdersPanelLayout.setVerticalGroup(
            viewOrdersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewOrdersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        manageMenuPan.addTab("View orders", viewOrdersPanel);

        jLabel1.setText("STUDENT MANAGER");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setText("Name: ");

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        firstNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstNameTextFieldKeyTyped(evt);
            }
        });

        jLabel4.setText("Suname:");

        surnameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameTextFieldActionPerformed(evt);
            }
        });
        surnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                surnameTextFieldKeyTyped(evt);
            }
        });

        jLabel5.setText("Grade: ");

        gradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        gradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Class:");

        classComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "R", "E", "D", "A", "M" }));

        addStudentButton.setText("ADD STUDENT");
        addStudentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addStudentButtonMouseEntered(evt);
            }
        });
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        jLabel20.setText("ID number: ");

        IDtextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IDtextFieldKeyTyped(evt);
            }
        });

        errorMsgLabel.setText(" ");
        errorMsgLabel.setPreferredSize(new java.awt.Dimension(10, 10));

        jLabel22.setText("Date of birth:");

        jLabel21.setText("Print confirmation slip: ");

        confirmationSlipButtonGroup.add(yesradioButton);
        yesradioButton.setSelected(true);
        yesradioButton.setText("Yes");
        yesradioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesradioButtonActionPerformed(evt);
            }
        });

        confirmationSlipButtonGroup.add(noRadioButton);
        noRadioButton.setText("No");

        javax.swing.GroupLayout manageStudenstPanelLayout = new javax.swing.GroupLayout(manageStudenstPanel);
        manageStudenstPanel.setLayout(manageStudenstPanelLayout);
        manageStudenstPanelLayout.setHorizontalGroup(
            manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStudenstPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(IDtextField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DOBdatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                        .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                                    .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, manageStudenstPanelLayout.createSequentialGroup()
                                            .addGap(75, 75, 75)
                                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(97, 97, 97)
                                            .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel6)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, manageStudenstPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(29, 29, 29)
                                            .addComponent(gradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(68, 68, 68))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, manageStudenstPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addGap(18, 18, 18)
                                    .addComponent(yesradioButton)
                                    .addGap(50, 50, 50)
                                    .addComponent(noRadioButton)))
                            .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(errorMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, manageStudenstPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(213, 213, 213))
        );
        manageStudenstPanelLayout.setVerticalGroup(
            manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(manageStudenstPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55)
                        .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(surnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(classComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(59, 59, 59)
                .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(IDtextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(DOBdatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(manageStudenstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(yesradioButton)
                    .addComponent(noRadioButton)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(errorMsgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        manageMenuPan.addTab("Manage Students", manageStudenstPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageMenuPan, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageMenuPan)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addItemtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemtButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemtButtonActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void gradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeComboBoxActionPerformed
        // TODO add your handling code here:
        errorMsgLabel.setText("");
    }//GEN-LAST:event_gradeComboBoxActionPerformed

    private void IDtextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IDtextFieldKeyTyped
        // TODO add your handling code here:
           IDtextField.setBackground(Color.white);
           errorMsgLabel.setText("");
       
    }//GEN-LAST:event_IDtextFieldKeyTyped

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
        
         String firstName = firstNameTextField.getText(); 
         String surname = surnameTextField.getText(); 
         String idNumber = IDtextField.getText(); 
         String sClass = (String) (classComboBox.getSelectedItem());
         int grade = 0;
         String gradeStr = (String)gradeComboBox.getSelectedItem();
         LocalDate dob = DOBdatePicker.getDate(); 
         
         //check if id
         

         
         if(firstName.isBlank() ||  !Student.isValidFirstName(firstName)){ 
             firstNameTextField.setBackground(Color.red);
             errorMsgLabel.setText("First name not valid");
             errorMsgLabel.setForeground(Color.red);
            
         }
         else if(surname.isBlank() || !Student.isValidLastName(surname)){ 
              surnameTextField.setBackground(Color.red);
             errorMsgLabel.setText("Surname not valid");
             errorMsgLabel.setForeground(Color.red);
         }
         else if(idNumber.isBlank() || !Student.isValidID(idNumber) ){ 
             IDtextField.setBackground(Color.red);
             errorMsgLabel.setText("ID num not valid");
             errorMsgLabel.setForeground(Color.red);
         }
         else if(sClass.compareToIgnoreCase("-") == 0){ 
             errorMsgLabel.setText("Please select a class");
             errorMsgLabel.setForeground(Color.red);
         }
         else if(gradeStr.equals("-")){ 
            errorMsgLabel.setText("Please select a grade");
            errorMsgLabel.setForeground(Color.red);
         }
         else if(!Student.isValidDOB(idNumber, dob)){ 
             errorMsgLabel.setText("Date of birth does not match ID Number");
             errorMsgLabel.setForeground(Color.red);
             
         }
         
         else {
             grade = Integer.parseInt(gradeStr); 
             JOptionPane.showMessageDialog(null, "Student successfully added");
             firstNameTextField.setText("");
             surnameTextField.setText("");
             IDtextField.setText("");
             gradeComboBox.setSelectedIndex(0);
             DOBdatePicker.setDateToToday();
             classComboBox.setSelectedIndex(0);
             confirmationSlipButtonGroup.setSelected(yesradioButton.getModel(), true);
             
             //s.addStudent(idNumber, firstName, surname, sClass, grade, dob);
         } 
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void surnameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameTextFieldActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_surnameTextFieldActionPerformed

    private void firstNameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstNameTextFieldKeyTyped
        // TODO add your handling code here:
        firstNameTextField.setBackground(Color.white);
        errorMsgLabel.setText("");
    }//GEN-LAST:event_firstNameTextFieldKeyTyped

    private void surnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_surnameTextFieldKeyTyped
        // TODO add your handling code here:
           surnameTextField.setBackground(Color.white);
        errorMsgLabel.setText("");
    }//GEN-LAST:event_surnameTextFieldKeyTyped

    private void DOBdatePickerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_DOBdatePickerPropertyChange
        // TODO add your handling code here:  
         DOBdatePicker.setBackground(Color.white);
        errorMsgLabel.setText("");
        
    }//GEN-LAST:event_DOBdatePickerPropertyChange

    private void yesradioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesradioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yesradioButtonActionPerformed

    private void addStudentButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addStudentButtonMouseEntered
    }//GEN-LAST:event_addStudentButtonMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.DatePicker DOBdatePicker;
    private javax.swing.JPanel FAQsPanel;
    private javax.swing.JTextField IDtextField;
    private javax.swing.JCheckBox SaladCheckBox;
    private javax.swing.JButton addItemtButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton addWaiterButton;
    private javax.swing.JCheckBox allCheckbox;
    private javax.swing.JComboBox<String> classComboBox;
    private javax.swing.ButtonGroup confirmationSlipButtonGroup;
    private javax.swing.JButton deleteItemButton;
    private javax.swing.JButton deleteWaiterButton;
    private javax.swing.JCheckBox drinkCheckBox;
    private javax.swing.JButton editItemButton;
    private javax.swing.JButton editWaiterButton;
    private javax.swing.JLabel errorMsgLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JComboBox<String> gradeComboBox;
    private javax.swing.JTextField itemNameTextField;
    private javax.swing.JComboBox<String> itemTypeComboBox;
    private javax.swing.JTextField itempricetextField;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton leastSoldRadioButton;
    private javax.swing.JTabbedPane manageMenuPan;
    private javax.swing.JPanel manageMenuPanel;
    private javax.swing.JPanel manageStudenstPanel;
    private javax.swing.JPanel manageWorkersPanel;
    private javax.swing.JTable menuTable;
    private javax.swing.JRadioButton mostSoldradioButton;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JTable ordersTable;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JTable salesTable;
    private javax.swing.JCheckBox sandwichtextBox;
    private javax.swing.JCheckBox snackCheckbox;
    private javax.swing.ButtonGroup soldButtonGroup;
    private javax.swing.JTextField surnameTextField;
    private javax.swing.JPanel viewOrdersPanel;
    private javax.swing.JButton viewPasswordButton;
    private javax.swing.JButton viewSalesButton;
    private javax.swing.JPanel viewSalesPanel;
    private javax.swing.JTextField waiterNameTextField;
    private javax.swing.JTextField waiterUsernameTextField;
    private javax.swing.JTable workersTable;
    private javax.swing.JCheckBox wrapCheckBox;
    private javax.swing.JRadioButton yesradioButton;
    // End of variables declaration//GEN-END:variables
}
